name: usgs_env
channels:
- anaconda-fusion
- defaults
- conda-forge
dependencies:
- python=3.6.1
- jsonschema
- python-dateutil
- six
- xmltodict
- beautifulsoup4
- pip
- python=3.6.1
- requests
- setuptools
- wheel
