# simple program to extract the row/path from the CSV generated by a usgs fetch command

import argparse

def process(input_path, output_path):
    row_paths = set()

    with open(input_path) as f:
        for line in f.readlines():
            items = line.split(",")
            id = items[2].strip()
            path = int(id[3:6])
            row = int(id[6:9])
            row_paths.add((row,path))

    with open(output_path,"w") as f:
        f.write("row,path")
        for (row,path) in row_paths:
            f.write(f"\n{row},{path}")

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument("--input-path",default="search.csv")
    parser.add_argument("--output-path",default="row_path.csv")
    args = parser.parse_args()
    process(args.input_path, args.output_path)
